### ISSUE TITLE
Voronoi diagram broken

### ISSUE THREAD

**Issue by BagelOrb** [boostorg/polygon#32]
I've been stress-testing the Voronoi diagram builder and I have concluded that the library doesn't produce stable results when the input data gets a little complex.

My test cases consists of random polygons without self-overlap.

Here's one arbitrary case which shows severe problems:
![image](https://user-images.githubusercontent.com/8895761/58310635-653edc00-7e07-11e9-8b1e-c339f5424d00.png)
Input segments in black, voronoi edges in red, voronoi parabolas in blue (with low discretization), infinite edges not drawn.

Here's the segments which produce the erroneous case above: 
[boost_voronoi_problem.txt](https://github.com/boostorg/polygon/files/3215716/boost_voronoi_problem.txt)

**Comment by asydorchuk** [comment]
Hi @BagelOrb, could you make sure that segments don't intersect except endpoints?
If they do, you need to split segments at intersection points.

This is mentioned in the docs:
```
Input points and segments should not overlap except their endpoints. This means that input point should not lie inside the input segment and input segments should not intersect except their endpoints.
```

**Comment by BagelOrb** [comment]
They don't seem to intersect, though in some places the segments are touching.
![image](https://user-images.githubusercontent.com/8895761/58319384-1a7a8f80-7e1a-11e9-8e18-304445fe8b8f.png)

**Comment by BagelOrb** [comment]
I guess it does have self-intersections after all.

These polygons were generated by ClipperLib and due to rounding errors there are cases which end up being handled as self-intersections.

**Comment by BagelOrb** [comment]
Thanks for pointing it out. It should have been obvious, but I thought I was sure there were no self-intersections. I already gave up on boost. I'm really happy I can still get it working.

**Comment by asydorchuk** [comment]
No problem, glad to help! You could also try to scale the coordinates (by a factor of 1e3 or 1e6), to potentially avoid self intersections after rounding. If that doesn't work some preprocessing is necessary.

**Comment by BagelOrb** [comment]
Performing an offset of -5 using ClipperLib already solves the problem.
5 is probably within the range of rounding errors, since Clipper works with integer logic.
