### ISSUE TITLE
List of non BOOST-prefixed macros

### ISSUE THREAD

**Issue by ned14** [boostorg/polygon#33]
The following macros are missing a BOOST_ prefix, which is against Boost library guidelines:

```
./boost/polygon/gtl.hpp:#ifndef GTL_GTL_HPP
./boost/polygon/gtl.hpp:#define GTL_GTL_HPP
```

**Comment by glenfe** [comment]
Resolved in 596ea34b36911f959d45f02089fd2bf462d9377b.
